import re

# Read orchestrator
with open('agents/orchestrator.py', 'r') as f:
    content = f.read()

# Fix the file writing logic to actually create files
new_write_logic = '''    def _handle_edit_commands(self, commands: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Handle file edit commands with better error handling"""
        
        results = []
        total_changed_lines = 0
        
        for cmd in commands:
            if "write" in cmd:
                write_data = cmd["write"]
                file_path = write_data["path"]
                
                if self.debug:
                    print(f"📝 Writing to: {file_path}")
                
                # Safety check
                if not self._is_safe_path(file_path):
                    results.append({
                        "command": cmd,
                        "success": False, 
                        "error": f"Unsafe path: {file_path}"
                    })
                    continue
                
                try:
                    # Get content to write
                    if "patch" in write_data:
                        content_to_write = write_data["patch"]
                    elif "content" in write_data:
                        content_to_write = write_data["content"]
                    else:
                        content_to_write = "// Auto-generated by Claude agent"
                    
                    # Actually write the file
                    write_result = self.repo.write_file(file_path, content_to_write)
                    
                    if self.debug:
                        print(f"✅ File written: {write_result}")
                    
                    results.append({
                        "command": cmd,
                        "success": True,
                        "result": write_result,
                        "file_created": True
                    })
                    
                except Exception as e:
                    if self.debug:
                        print(f"❌ File write error: {e}")
                    results.append({
                        "command": cmd,
                        "success": False,
                        "error": str(e)
                    })
        
        return {"success": True, "results": results, "files_created": len([r for r in results if r.get("success")])}'''

# Replace the method
pattern = r'def _handle_edit_commands.*?(?=\n    def|\nclass|\Z)'
content = re.sub(pattern, new_write_logic + '\n\n', content, flags=re.DOTALL)

with open('agents/orchestrator.py', 'w') as f:
    f.write(content)

print("✅ Fixed file creation logic")
